name = "PAMG"
uuid = "be92dbc9-a157-4fa4-abfb-0b237afea198"
authors = ["Quesys-tech"]
version = "0.1.0"

[compat]
julia = "1.7" #1.7 or later 

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
